language: ruby
before_install:
  - gem update --system
  - gem --version
bundler_args: --without development
rvm:
  - jruby-18mode
  - jruby-19mode
env:
  - IDENTITY_MAP="true"
  - IDENTITY_MAP="false"